#Common-Crawl CDX Server Config
#archive_paths: https://commoncrawl.s3.amazonaws.com/
archive_paths: s3://commoncrawl/

# suffix to add to collection for cdx api
cdx_api_endpoint: -index

enable_memento: true

shard_index_loc:
    match: '.*(collections/[^/]+/)'
    #replace: 'http://commoncrawl.s3.amazonaws.com/cc-index/\1'
    replace: 's3://commoncrawl/cc-index/\1'

# this is also the default page size
max_blocks: 5

# disable framed replay mode
framed_replay: false

# enable JSON listing of available collections /collinfo.json
enable_coll_info: true
